"""Static analysis scanner for Cargo (Rust) packages."""

from pathlib import Path
from typing import Literal

from pydantic import BaseModel

from app.core.config import Settings
from app.scanners.patterns.cargo_patterns import ALL_CARGO_PATTERNS, BUILD_RS_ONLY_NAMES
from app.schemas.package import PackageInfo
from app.schemas.scan import ScanResult

_SEVERITY_ORDER: dict[str, int] = {"low": 0, "medium": 1, "high": 2, "critical": 3}

# build.rs gets severity boost — it runs at compile time
_BUILD_RS_SEVERITY_BOOST = 1
_SEVERITY_NAMES = ["low", "medium", "high", "critical"]

_FALSE_POSITIVE_INDICATORS = [
    "// Generated by",
    "// DO NOT EDIT",
    "bindgen",
    "cc::Build",
    "pkg_config",
    "cmake::Config",
    "autocfg",
]


class PatternMatch(BaseModel):
    pattern_name: str
    severity: Literal["low", "medium", "high", "critical"]
    line_number: int
    line_content: str
    file_path: str
    description: str


class CargoStaticAnalysisScanner:
    """Pattern-matching scanner for Cargo/Rust packages."""

    def __init__(self, settings: Settings) -> None:
        self._threshold = settings.static_analysis_severity_threshold
        self._threshold_level = _SEVERITY_ORDER[self._threshold]

    async def scan(self, package: PackageInfo, artifacts: list[Path]) -> ScanResult:
        all_matches: list[PatternMatch] = []

        for artifact_path in artifacts:
            if not artifact_path.exists() or not artifact_path.is_file():
                continue

            try:
                content = artifact_path.read_text(errors="replace")
            except OSError:
                continue

            has_safe_indicators = self._is_likely_safe(content)
            is_build_rs = artifact_path.name == "build.rs"

            matches = self._scan_content(content, artifact_path.name, is_build_rs)

            if has_safe_indicators:
                for m in matches:
                    if m.severity == "critical":
                        m.severity = "high"

            all_matches.extend(matches)

        filtered = [m for m in all_matches if _SEVERITY_ORDER[m.severity] >= self._threshold_level]

        if not filtered:
            return ScanResult(
                scanner_name="static_analysis",
                verdict="pass",
                confidence=0.9,
                details="No suspicious patterns detected in Cargo package",
            )

        verdict, confidence = self._calculate_verdict(filtered)
        details = self._build_details(filtered)

        return ScanResult(
            scanner_name="static_analysis",
            verdict=verdict,
            confidence=confidence,
            details=details,
            metadata={
                "match_count": len(filtered),
                "matches": [m.model_dump() for m in filtered[:10]],
            },
        )

    def _scan_content(self, content: str, source: str, is_build_rs: bool) -> list[PatternMatch]:
        matches: list[PatternMatch] = []
        lines = content.split("\n")

        for line_num, line in enumerate(lines, start=1):
            for pattern in ALL_CARGO_PATTERNS:
                # Skip build.rs-only patterns for non-build.rs files
                if pattern.name in BUILD_RS_ONLY_NAMES and not is_build_rs:
                    continue
                if pattern.pattern.search(line):
                    severity = pattern.severity
                    # Boost severity for build.rs (compile-time execution)
                    if is_build_rs and _SEVERITY_ORDER[severity] < 3:
                        boosted = min(_SEVERITY_ORDER[severity] + _BUILD_RS_SEVERITY_BOOST, 3)
                        severity = _SEVERITY_NAMES[boosted]
                    matches.append(
                        PatternMatch(
                            pattern_name=pattern.name,
                            severity=severity,
                            line_number=line_num,
                            line_content=line.strip()[:200],
                            file_path=source,
                            description=f"{pattern.description}{' (in build.rs)' if is_build_rs else ''}",
                        )
                    )

        # Multiline patterns (re.DOTALL)
        for pattern in ALL_CARGO_PATTERNS:
            if not (pattern.pattern.flags & 16):  # re.DOTALL = 16
                continue
            if pattern.name in BUILD_RS_ONLY_NAMES and not is_build_rs:
                continue
            m = pattern.pattern.search(content)
            if m:
                line_num = content[: m.start()].count("\n") + 1
                matches.append(
                    PatternMatch(
                        pattern_name=pattern.name,
                        severity=pattern.severity,
                        line_number=line_num,
                        line_content=m.group(0).replace("\n", " ")[:200],
                        file_path=source,
                        description=pattern.description,
                    )
                )

        return matches

    @staticmethod
    def _is_likely_safe(content: str) -> bool:
        return any(indicator in content for indicator in _FALSE_POSITIVE_INDICATORS)

    @staticmethod
    def _calculate_verdict(
        matches: list[PatternMatch],
    ) -> tuple[Literal["pass", "warn", "fail"], float]:
        max_severity = max(_SEVERITY_ORDER[m.severity] for m in matches)
        if max_severity >= _SEVERITY_ORDER["critical"]:
            return "fail", min(1.0, 0.7 + len(matches) * 0.05)
        if max_severity >= _SEVERITY_ORDER["high"]:
            if len(matches) >= 2:
                return "fail", min(0.9, 0.6 + len(matches) * 0.05)
            return "warn", 0.7
        if max_severity >= _SEVERITY_ORDER["medium"]:
            if len(matches) >= 3:
                return "warn", 0.7
            return "warn", 0.5
        return "pass", 0.6

    @staticmethod
    def _build_details(matches: list[PatternMatch]) -> str:
        unique_patterns = {m.pattern_name: m.description for m in matches}
        lines = [f"Found {len(matches)} suspicious pattern(s) in Cargo package:"]
        for name, desc in unique_patterns.items():
            count = sum(1 for m in matches if m.pattern_name == name)
            lines.append(f"  - {desc} ({name}): {count} occurrence(s)")
        return "\n".join(lines)
