"""Static analysis scanner for Go module packages."""

from pathlib import Path
from typing import Literal

from pydantic import BaseModel

from app.core.config import Settings
from app.scanners.patterns.go_patterns import ALL_GO_PATTERNS, GOMOD_PATTERNS
from app.schemas.package import PackageInfo
from app.schemas.scan import ScanResult

_SEVERITY_ORDER: dict[str, int] = {"low": 0, "medium": 1, "high": 2, "critical": 3}
_SEVERITY_NAMES = ["low", "medium", "high", "critical"]

# Go build tools that commonly use exec.Command or go:generate
_FALSE_POSITIVE_INDICATORS = [
    "Code generated by",
    "DO NOT EDIT",
    "stringer",
    "protoc-gen-go",
    "mockgen",
    "go-bindata",
    "esc -o",
]


class PatternMatch(BaseModel):
    pattern_name: str
    severity: Literal["low", "medium", "high", "critical"]
    line_number: int
    line_content: str
    file_path: str
    description: str


class GoStaticAnalysisScanner:
    """Pattern-matching scanner for Go module source code."""

    def __init__(self, settings: Settings) -> None:
        self._threshold = settings.static_analysis_severity_threshold
        self._threshold_level = _SEVERITY_ORDER[self._threshold]

    async def scan(self, package: PackageInfo, artifacts: list[Path]) -> ScanResult:
        all_matches: list[PatternMatch] = []

        for artifact_path in artifacts:
            if not artifact_path.exists() or not artifact_path.is_file():
                continue

            try:
                content = artifact_path.read_text(errors="replace")
            except OSError:
                continue

            has_safe_indicators = self._is_likely_safe(content)

            if artifact_path.name == "go.mod":
                matches = self._scan_gomod(content, artifact_path.name)
            else:
                matches = self._scan_go_source(content, artifact_path.name)

            if has_safe_indicators:
                _NEVER_DOWNGRADE = {
                    "reverse_shell",
                    "crypto_miner",
                    "cloud_metadata",
                    "cloud_metadata_access",
                    "cloud_metadata_expanded",
                    "ssh_key_access",
                    "aws_credential_access",
                    "destructive_command",
                    "procfs_access",
                    "k8s_secret_access",
                    "system_binary_write",
                    "git_hook_write",
                    "dll_hijacking",
                    "known_c2_domain",
                    "known_c2_ip",
                    "crontab_write",
                    "systemd_write",
                    "launchd_write",
                    "sitecustomize_write",
                    "ld_preload_inject",
                    "base64_exec",
                    "base64_eval",
                    "getattr_exec",
                    "libc_system",
                    "crontab_persistence",
                    "webhook_exfiltration",
                    "etc_passwd",
                    "base64_decode_exec",
                    "build_rs_shell",
                }
                for m in matches:
                    if m.severity == "critical" and m.pattern_name not in _NEVER_DOWNGRADE:
                        m.severity = "high"

            all_matches.extend(matches)

        filtered = [m for m in all_matches if _SEVERITY_ORDER[m.severity] >= self._threshold_level]

        if not filtered:
            return ScanResult(
                scanner_name="static_analysis",
                verdict="pass",
                confidence=0.9,
                details="No suspicious patterns detected in Go module",
            )

        verdict, confidence = self._calculate_verdict(filtered)
        details = self._build_details(filtered)

        return ScanResult(
            scanner_name="static_analysis",
            verdict=verdict,
            confidence=confidence,
            details=details,
            metadata={
                "match_count": len(filtered),
                "matches": [m.model_dump() for m in filtered[:10]],
            },
        )

    def _scan_go_source(self, content: str, source: str) -> list[PatternMatch]:
        """Scan Go source file against all non-gomod patterns."""
        matches: list[PatternMatch] = []
        lines = content.split("\n")

        # Single-line patterns (exclude gomod-only patterns)
        gomod_names = {p.name for p in GOMOD_PATTERNS}
        for line_num, line in enumerate(lines, start=1):
            for pattern in ALL_GO_PATTERNS:
                if pattern.name in gomod_names:
                    continue
                if pattern.pattern.search(line):
                    matches.append(
                        PatternMatch(
                            pattern_name=pattern.name,
                            severity=pattern.severity,
                            line_number=line_num,
                            line_content=line.strip()[:200],
                            file_path=source,
                            description=pattern.description,
                        )
                    )

        # Multiline patterns (already have re.DOTALL) — scan full content
        for pattern in ALL_GO_PATTERNS:
            if not (pattern.pattern.flags & 16):  # re.DOTALL = 16
                continue
            if pattern.name in gomod_names:
                continue
            m = pattern.pattern.search(content)
            if m:
                line_num = content[: m.start()].count("\n") + 1
                matches.append(
                    PatternMatch(
                        pattern_name=pattern.name,
                        severity=pattern.severity,
                        line_number=line_num,
                        line_content=m.group(0).replace("\n", " ")[:200],
                        file_path=source,
                        description=pattern.description,
                    )
                )

        return matches

    def _scan_gomod(self, content: str, source: str) -> list[PatternMatch]:
        """Scan go.mod file against gomod-specific patterns."""
        matches: list[PatternMatch] = []
        lines = content.split("\n")

        for line_num, line in enumerate(lines, start=1):
            for pattern in GOMOD_PATTERNS:
                if pattern.pattern.search(line):
                    matches.append(
                        PatternMatch(
                            pattern_name=pattern.name,
                            severity=pattern.severity,
                            line_number=line_num,
                            line_content=line.strip()[:200],
                            file_path=source,
                            description=pattern.description,
                        )
                    )

        return matches

    @staticmethod
    def _is_likely_safe(content: str) -> bool:
        return any(indicator in content for indicator in _FALSE_POSITIVE_INDICATORS)

    @staticmethod
    def _calculate_verdict(
        matches: list[PatternMatch],
    ) -> tuple[Literal["pass", "warn", "fail"], float]:
        max_severity = max(_SEVERITY_ORDER[m.severity] for m in matches)

        if max_severity >= _SEVERITY_ORDER["critical"]:
            return "fail", min(1.0, 0.7 + len(matches) * 0.05)

        if max_severity >= _SEVERITY_ORDER["high"]:
            return "fail", min(0.9, 0.6 + len(matches) * 0.05)

        if max_severity >= _SEVERITY_ORDER["medium"]:
            if len(matches) >= 3:
                return "warn", 0.7
            return "warn", 0.5

        return "pass", 0.6

    @staticmethod
    def _build_details(matches: list[PatternMatch]) -> str:
        unique_patterns = {m.pattern_name: m.description for m in matches}
        lines = [f"Found {len(matches)} suspicious pattern(s) in Go module:"]
        for name, desc in unique_patterns.items():
            count = sum(1 for m in matches if m.pattern_name == name)
            lines.append(f"  - {desc} ({name}): {count} occurrence(s)")
        return "\n".join(lines)
